### ISSUE TITLE
Error: PostCSS plugin tailwindcss requires PostCSS 8

### ISSUE THREAD

**Issue by zoxon** [vixalien/explosiv#7]
```sh
npm run dev

Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/zoxon/work/explosiv/node_modules/explosiv/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/zoxon/work/explosiv/node_modules/explosiv/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/zoxon/work/explosiv/node_modules/explosiv/node_modules/postcss/lib/postcss.js:55:10)
    at Object.buildStatic [as static] (/Users/zoxon/work/explosiv/node_modules/explosiv/dist/cli.js:30:28)
    at async build2 (/Users/zoxon/work/explosiv/node_modules/explosiv/dist/cli.js:193:7)
    at async buildWithSpinner (/Users/zoxon/work/explosiv/node_modules/explosiv/dist/cli.js:246:7)
    at async FSWatcher.<anonymous> (/Users/zoxon/work/explosiv/node_modules/explosiv/dist/cli.js:256:5)
Development server is live at: http://localhost:3000
```

I tried to install postcss locally but this didn't helps

**Comment by vixalien** [comment]
thank you for noticing this I think your PR fixes this and it'll hopefully be merged soon.

if not, a PR would be recommended because I'm currently AFK.
